export const stages = [
  {
    id: "inputs",
    label: "Surface observations",
    short: "Observe",
    shape: "84 × 100 × 240",
    meta: "7 days · 12 features",
    title: "Give the surface a memory.",
    description:
      "Daily observations are aligned on the same quarter-degree grid, normalized, and stacked across seven days. Surface temperature, sea level, salinity, currents, and physical context enter as 84 channels.",
    operation: "Regrid → normalize → stack",
    output: "84 × 100 × 240",
    scene: 0,
  },
  {
    id: "fusion",
    label: "Temporal fusion",
    short: "Fuse",
    shape: "12 × 100 × 240",
    meta: "7 days → 1 surface state",
    title: "Seven days. One coherent state.",
    description:
      "A lightweight temporal convolution combines the seven daily snapshots into a twelve-channel surface state. It gives the network a short history of the forcing that shapes the ocean below.",
    operation: "1D convolution across time",
    output: "12 × 100 × 240",
    scene: 1,
  },
  {
    id: "encoder",
    label: "Attention encoder",
    short: "Encode",
    shape: "64 → 128 → 256",
    meta: "Channel + spatial attention",
    title: "Learn what matters. And where.",
    description:
      "Three encoder blocks extract progressively broader spatial patterns. Each combines convolution, batch normalization, ELU, and CBAM attention before pooling. Channel attention weights features; spatial attention weights locations.",
    operation: "Conv → BN → ELU → CBAM → pool",
    output: "256 × 12 × 30",
    scene: 2,
  },
  {
    id: "embedding",
    label: "Satellite embedding",
    short: "Embed",
    shape: "512 × 12 × 30",
    meta: "The compact ocean representation",
    title: "The ocean, in a learned code.",
    description:
      "At the bottleneck, each spatial location holds a 512-dimensional learned representation. It is designed to summarize surface dynamics and the relationships that inform subsurface temperature structure.",
    operation: "Conv 256 → 512 → BN → ELU → CBAM",
    output: "512 × 12 × 30",
    scene: 3,
  },
  {
    id: "decoder",
    label: "Reconstruction decoder",
    short: "Decode",
    shape: "256 → 128 → 64",
    meta: "Spatial detail, restored",
    title: "Bring the fine detail back.",
    description:
      "Three upsampling blocks restore the original grid. Skip connections carry fine-scale information from the matching encoder resolutions, preserving local structure while the embedding provides broader context.",
    operation: "Upsample → concatenate skip → Conv → CBAM",
    output: "64 × 100 × 240",
    scene: 4,
  },
  {
    id: "output",
    label: "Subsurface temperature",
    short: "Reconstruct",
    shape: "15 × 100 × 240",
    meta: "15 depths · 0–1,000 metres",
    title: "Fifteen depths. Together.",
    description:
      "A single 1 × 1 convolution projects the restored feature map into fifteen temperature layers at once. The shared decoder connects the depth estimates within one learned vertical reconstruction.",
    operation: "1 × 1 convolution: 64 → 15",
    output: "15 × 100 × 240",
    scene: 5,
  },
];
export const features = [
  {
    symbol: "SST",
    name: "Sea surface temperature",
    source: "OSTIA",
    kind: "observed",
    why: "The direct thermal boundary at the ocean surface, providing a strong starting point for reconstructing temperatures beneath it.",
  },
  {
    symbol: "∇SST",
    name: "Temperature gradient",
    source: "Derived from SST",
    kind: "derived",
    why: "Log-magnitude gradients describe fronts and eddy boundaries that a temperature value alone cannot capture.",
  },
  {
    symbol: "SSH",
    name: "Sea surface height",
    source: "DUACS",
    kind: "observed",
    why: "Absolute dynamic topography carries information about ocean circulation and the integrated density structure above the thermocline.",
  },
  {
    symbol: "∇SSH",
    name: "Height gradient",
    source: "Derived from SSH",
    kind: "derived",
    why: "Spatial gradients reveal frontal sharpness and the geostrophic current structures associated with subsurface variability.",
  },
  {
    symbol: "SSS",
    name: "Sea surface salinity",
    source: "SMAP / SMOS",
    kind: "observed",
    why: "Freshwater and salinity patterns help describe haloclines and barrier layers, particularly in the Bay of Bengal.",
  },
  {
    symbol: "WSC",
    name: "Wind stress curl",
    source: "Derived from wind",
    kind: "derived",
    why: "The curl of wind stress represents Ekman pumping and suction. This physically meaningful signal replaces raw wind components in the model.",
  },
  {
    symbol: "U",
    name: "Zonal surface current",
    source: "OSCAR",
    kind: "observed",
    why: "East–west transport contributes information about circulation and the redistribution of heat across the domain.",
  },
  {
    symbol: "V",
    name: "Meridional surface current",
    source: "OSCAR",
    kind: "observed",
    why: "North–south transport complements the zonal current and describes how surface heat moves through the North Indian Ocean.",
  },
  {
    symbol: "H",
    name: "Bathymetry",
    source: "ETOPO",
    kind: "context",
    why: "Seafloor depth gives the network geographic context for marginal seas, shelves, and the available water column.",
  },
  {
    symbol: "φ",
    name: "Latitude",
    source: "Static grid",
    kind: "context",
    why: "Latitude locates regional differences in the relationship between the surface and subsurface ocean.",
  },
  {
    symbol: "λ",
    name: "Longitude",
    source: "Static grid",
    kind: "context",
    why: "Longitude distinguishes the east–west geography of the domain, including Arabian Sea and Bay of Bengal regimes.",
  },
  {
    symbol: "DOY",
    name: "Day of year",
    source: "Calendar",
    kind: "context",
    why: "A normalized seasonal coordinate gives the model context for the monsoon cycle. It changes with the date rather than with location.",
  },
];
export const zones = {
  mixed:
    "The mixed layer uses baseline weight. Its temperatures are relatively well constrained by the observed sea surface temperature.",
  thermocline:
    "The thermocline receives twice the weight: its steep temperature gradients make reconstruction particularly challenging.",
  deep: "The deeper ocean uses half weight, balancing its smoother temperature structure against the more variable upper layers.",
};
